spring.application.name=Soundora

#-----------BANCO DE DADOS POSTGRES-----------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=xQz0Y2t6XwJqv7v5kK4YQJtA5QhN2x8x4fKQ9KQ5Y9o=
jwt.expiration=86400000
